/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Crash Protection
 #	author : miyako
 #	2016/12/22
 #
 # --------------------------------------------------------------------------------*/


void InitPlugin();
void DeinitPlugin();

// --- Crash Protection
void NSFunctionBarAPIEnabled(sLONG_PTR *pResult, PackagePtr pParams);
void doIt();